on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

name: lint and test

jobs:
  unit-tests:
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.6.11"

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync

      - name: Test docs build
        run: make sphinx

      - name: Run lint
        run: make lint-all

      - name: Run coverage
        run: uv run pytest --cov-report=xml:coverage.xml --cov=fiderpy/ tests/

      - name: Codecov
        if: success()
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
          flags: unittests-py${{ matrix.python-version }}

  create-release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: [unit-tests]
    uses: nickatnight/gha-workflows/.github/workflows/create-release.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  upload-release-to-pypi:
    needs: [unit-tests]
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.6.11"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Build the package
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
